language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install .
  - pip install -rrequirements.txt
script: coverage run -m pytest -k "not copy"
notifications:
  email: 
    - petergoldsborough@hotmail.com
after_success:
  - coveralls
  - curl -X POST https://readthedocs.org/build/lnk