language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq xclip
install:
  - "pip install ."
  - "pip install -rrequirements.txt"
script: coverage run -m pytest
notifications:
  email: 
    - petergoldsborough@hotmail.com
after_success:
  - coveralls